apiVersion: example.example.com/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: my-controller
    app.kubernetes.io/managed-by: kustomize
  name: task-sample
spec:
  # TODO(user): Add fields here
